version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: db
    networks:
      - auto

  customer-api:
    build: ./ALTEN-CUS
    restart: always
    container_name: customer-api
    depends_on:
      - "mongo"
    ports:
      - "5000:80"
    environment:
      NODE_ENV: production
    networks:
      - auto
networks:
    auto: {}
