version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: db
    networks:
      - auto

  customer-api:
    build: ./ALTEN-CUS
    restart: always
    container_name: customer-api
    depends_on:
      - "mongo"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - auto

  vehicle-api:
    build: ./ALTEN-VEHICLE
    restart: always
    container_name: vehicle-api
    depends_on:
      - "mongo"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    networks:
      - auto

  ping:
    build: ./ALTEN-SIM-PING
    restart: always
    container_name: ping
    depends_on:
      - "hub"
    ports:
      - "8080:3000"
      - "8090:8090"
    environment:
      NODE_ENV: production
    networks:
      - auto
  
  hub:
    build: ./ALTEN-PING-HUB
    restart: always
    container_name: hub
    depends_on:
      - "vehicle-api"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    networks:
      - auto
  
  web_app:
    build: ./ALTEN-WEB
    restart: always
    container_name: web_app
    depends_on:
      - "vehicle-api"
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production
    networks:
      - auto



networks:
    auto: {}
